// M6 Stage 3: the GLM tokenizer's differential gate — our encode/decode
// vs HF tokenizers 0.23.1 goldens (tests/data/glm_tokenizer_goldens.jsonl,
// generated by tools/gen_tokenizer_goldens.py). The corpus header carries
// the tokenizer.json FNV-1a-64 revision hash; a mismatched revision
// refuses the run (the goldens are keyed to one checkpoint revision).
//
// Hand-carried anchors (the fabric-run prompts/generations — ids the
// model actually consumed in the M6 Stage 1d/2 records) are asserted
// before the corpus: "The capital of France is" and " Paris"/"." are the
// first tokens of the recorded transcripts.
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "text/tokenizer.hpp"
#include "text/tool_parser.hpp"
#include "text/tool_grammar.hpp"
#include "text/unicode_normalize.hpp"

namespace {

// The corpus path comes from argv[1] (ctest passes the source-tree path;
// the repo-root-relative default covers manual runs).
std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1] : "tests/data/glm_tokenizer_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

// The corpus header's "model" (the Qwen corpus names its checkpoint);
// empty when absent.
std::string golden_model(const std::string& path) {
  std::ifstream f(path);
  std::string first;
  if (!f || !std::getline(f, first)) return "";
  const size_t m = first.find("\"model\": \"");
  if (m == std::string::npos) return "";
  const size_t e = first.find('"', m + 10);
  return e == std::string::npos ? "" : first.substr(m + 10, e - (m + 10));
}
std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

DGPP_TEST(glm_tokenizer_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  // Resolve tokenizer.json via the HF cache (the deployment location;
  // the same snapshot id every node carries). Missing cache = skip (rc 2).
  // The model: DGPP_TP_REAL_MODEL, else the corpus header's, else GLM.
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  std::string model_id = golden_model(kGoldenPath);
  if (env_model && *env_model) model_id = env_model;
  if (model_id.empty()) model_id = "unsloth/GLM-5.3-Flash-FP8";
  const bool qwen = model_id.find("Qwen") != std::string::npos;
  const bool mimo = model_id.find("MiMo") != std::string::npos;
  const bool dsv41 = model_id.find("DeepSeek-V4") != std::string::npos;
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_tokenizer_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const std::string tok_path =
      (std::filesystem::path(snap) / "tokenizer.json").string();

  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(tok_path);

  require(dgpp::text::ChatMarkers::from_tokenizer(tok).compact_tool_xml == mimo,
          "MiMo compact tool format is detected without changing other families");

  if (mimo) {
    using namespace dgpp::text;
    const auto def = dgpp::minijson::parse(
        R"({"name":"read_file","parameters":{"type":"object","properties":{"file_path":{"type":"string"},"offset":{"type":"integer"},"limit":{"type":"integer"}},"required":["file_path"],"additionalProperties":false}})");
    GrammarSpec spec;
    spec.mode = GrammarSpec::Mode::kAuto;
    spec.tools.push_back(grammar_tool_from_function(def.root, nullptr));
    // GrammarVocab needs a real EOS; read it from the tokenizer's role markers.
    int64_t eos = -1;
    for (const auto& t : tok.added_tokens()) if (t.content == "<|im_end|>") eos = t.id;
    require(eos >= 0, "MiMo EOS exists");
    const auto grammar_vocab = GrammarVocab::from_tokenizer(tok, {eos}, static_cast<int>(tok.max_id() + 1));
    GrammarState grammar(&grammar_vocab, spec, false);
    const std::string call = "<tool_call><function=read_file><parameter=file_path>astroid/builder.py</parameter><parameter=offset>80</parameter><parameter=limit>70</parameter></function></tool_call>";
    for (const int64_t id : tok.encode(call)) {
      require(grammar.allows(id), "native MiMo token rejected in " + std::string(grammar.state_name()) + ": " + tok.decode(id, false));
      grammar.advance(id);
    }
    require(std::string(grammar.state_name()) == "top", "native MiMo multi-argument call completes");
  }

  // Hand-carried anchors: the fabric-run prompt and first generations.
  if (dsv41) {
    // The DeepSeek-V4.1 corpus's first cases (HF tokenizers 0.23.2 on the
    // snapshot, 2026-09-13): the three-stage pre-tokenizer's plain words.
    require(tok.encode("The capital of France is") == std::vector<int64_t>{671, 6102, 294, 8760, 344},
            "deepseek anchor prompt does not encode to the recorded ids");
    require(tok.encode(" Paris") == std::vector<int64_t>{11111}, "deepseek anchor ' Paris' != id 11111");
    require(tok.decode(std::vector<int64_t>{11111, 16}, false) == " Paris.", "deepseek anchor does not decode to ' Paris.'");
  } else if (mimo) {
    require(tok.encode("The capital of France is") == std::vector<int64_t>{785, 6722, 315, 9625, 374},
            "MiMo anchor prompt does not encode to the HF ids");
    require(tok.encode(" Paris") == std::vector<int64_t>{12095}, "MiMo anchor Paris");
    require(tok.decode(std::vector<int64_t>{12095, 13}, false) == " Paris.", "MiMo anchor decode");
  } else if (!qwen) {
    const std::vector<int64_t> got =
        tok.encode("The capital of France is");
    const std::vector<int64_t> want{785, 6722, 315, 9621, 374};
    require(got == want,
                 "anchor prompt encodes to " + std::to_string(got.size()) +
                     " ids, expected 5: the fabric-run golden is the "
                     "hand-computed expectation");
    require(tok.decode(std::vector<int64_t>{12089, 13},
                            /*skip_special_tokens=*/false) == " Paris.",
                 "anchor generation does not decode to ' Paris.'");
    require(tok.encode(" Paris") ==
                     std::vector<int64_t>{12089},
                 "anchor ' Paris' != id 12089");
  } else {
    // The Q4 forward-check prompt (ids from HF tokenizers on the 5090 box)
    // and the model's answer.
    require(tok.encode("The capital of France is") ==
                std::vector<int64_t>{760, 6511, 314, 9338, 369},
            "qwen anchor prompt does not encode to the recorded ids");
    require(tok.encode(" Paris") == std::vector<int64_t>{11751}, "qwen anchor ' Paris' != id 11751");
    require(tok.decode(std::vector<int64_t>{11751}, false) == " Paris",
            "qwen anchor does not decode to ' Paris'");
  }

  // The corpus: header (revision key) + one line per case.
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(!lines.empty(), "golden corpus is empty");

  // The header's revision hash must equal this tokenizer.json's — a
  // different revision refuses rather than compares.
  {
    const size_t h = lines[0].find("\"revision_hash\": \"");
    require(h != std::string::npos, "malformed golden header");
    const std::string want = lines[0].substr(h + 18, 16);
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tok.revision_hash()));
    require(
        want == got,
        std::string("golden revision ") + want +
            " != tokenizer revision " + got +
            " — regenerate the goldens (tools/gen_tokenizer_goldens.py) "
            "for this checkpoint revision");
  }

  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    // Minimal field extraction (the corpus generator's own format; a
    // full JSON parse per line is overkill for {"text", "ids"}).
    const size_t t0 = lines[i].find("\"text\": \"");
    require(t0 != std::string::npos, "malformed corpus line");
    const size_t text_start = t0 + 9;
    // Unescape \uXXXX, \n, \t, \\, \" — the corpus writer escapes these.
    std::string text;
    for (size_t j = text_start; j < lines[i].size();) {
      const char c = lines[i][j];
      if (c == '"' && (j == 0 || lines[i][j - 1] != '\\')) break;
      if (c == '\\' && j + 1 < lines[i].size()) {
        const char e = lines[i][j + 1];
        if (e == 'n') text.push_back('\n');
        else if (e == 't') text.push_back('\t');
        else if (e == 'r') text.push_back('\r');
        else if (e == 'b') text.push_back('\b');
        else if (e == 'f') text.push_back('\f');
        else if (e == 'u') {
          const std::string hex = lines[i].substr(j + 2, 4);
          uint32_t cp =
              static_cast<uint32_t>(std::strtoul(hex.c_str(), nullptr, 16));
          // json.dumps escapes 4-byte codepoints as surrogate pairs.
          if (cp >= 0xD800 && cp <= 0xDBFF &&
              lines[i].compare(j + 6, 2, "\\u") == 0) {
            const std::string hex2 = lines[i].substr(j + 8, 4);
            const uint32_t lo = static_cast<uint32_t>(
                std::strtoul(hex2.c_str(), nullptr, 16));
            cp = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
            j += 6;
          }
          if (cp < 0x80) text.push_back(static_cast<char>(cp));
          else if (cp < 0x800) {
            text.push_back(static_cast<char>(0xC0 | (cp >> 6)));
            text.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
          } else if (cp < 0x10000) {
            text.push_back(static_cast<char>(0xE0 | (cp >> 12)));
            text.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
            text.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
          } else {
            text.push_back(static_cast<char>(0xF0 | (cp >> 18)));
            text.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
            text.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
            text.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
          }
          j += 6;
          continue;
        } else text.push_back(e);
        j += 2;
      } else {
        text.push_back(c);
        ++j;
      }
    }
    std::vector<int64_t> want;
    {
      const size_t i0 = lines[i].find("\"ids\": [");
      require(i0 != std::string::npos, "malformed corpus ids");
      const std::string ids =
          lines[i].substr(i0 + 8, lines[i].rfind(']') - i0 - 8);
      std::istringstream f(ids);
      std::string tok_id;
      while (f >> tok_id)
        want.push_back(std::strtoll(tok_id.c_str(), nullptr, 10));
    }

    const std::vector<int64_t> got = tok.encode(text);
    require(got == want,
                 "encode mismatch on case " + std::to_string(i) + " (" +
                     text + "): got " + std::to_string(got.size()) +
                     " ids, want " + std::to_string(want.size()));
    const std::string rt = tok.decode(got, /*skip_special_tokens=*/false);
    // An NFC tokenizer round-trips to the NFC form of the input.
    require(rt == text || ((qwen || mimo) && rt == dgpp::text::unicode::nfc(text)),
                 "verbatim round-trip mismatch on case " +
                     std::to_string(i) + ": got " + rt);
    ++checked;
  }
  DGPP_LOG_INFO("glm_tokenizer differential: {}/{} cases byte-exact "
                "(revision 0x{:016x})",
                checked, lines.size() - 1, tok.revision_hash());
}

DGPP_TEST(glm_tokenizer_boundary_contracts) {
  // Negative pins on the loader's strictness: these must THROW, not
  // guess. (Runs without the model cache: the checks are on the reject
  // paths, exercised through a bad file path / mangled shape.)
  bool threw = false;
  try {
    (void)dgpp::text::Tokenizer::load("/nonexistent/tokenizer.json");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "load of a missing file must throw");

  // A minimal malformed tokenizer.json (wrong pattern) must refuse with
  // the pinned-pattern message.
  // In the working directory (the build tree under ctest): a fixed /tmp
  // subdirectory came and went with other tools.
  const std::string tmp = "glm_tokenizer_test_bad_tokenizer.json";
  {
    std::ofstream f(tmp);
    f << R"({"version":"1.0","truncation":null,"padding":null,
"added_tokens":[],
"normalizer":null,
"pre_tokenizer":{"type":"Sequence","pretokenizers":[
 {"type":"Split","pattern":{"Regex":"wrong-pattern"},"behavior":"Isolated","invert":false},
 {"type":"ByteLevel","add_prefix_space":false,"trim_offsets":true,"use_regex":false}]},
"post_processor":{"type":"ByteLevel","add_prefix_space":true,"trim_offsets":false,"use_regex":true},
"decoder":{"type":"ByteLevel","add_prefix_space":true,"trim_offsets":true,"use_regex":true},
"model":{"type":"BPE","dropout":null,"unk_token":null,"continuing_subword_prefix":null,
"end_of_word_suffix":null,"fuse_unk":false,"byte_fallback":false,"ignore_merges":true,
"vocab":{},"merges":[]}})";
  }
  threw = false;
  std::string msg;
  try {
    (void)dgpp::text::Tokenizer::load(tmp);
  } catch (const std::exception& e) {
    threw = true;
    msg = e.what();
  }
  require(threw && msg.find("pinned regex") != std::string::npos,
               "a non-pinned Split pattern must refuse loudly (got: " + msg +
                   ")");
  std::remove(tmp.c_str());
}

}  // namespace

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return ::dgpp::test::run_all();
}
