#pragma once
// ByteLevel-BPE tokenizer for the supported GLM, Qwen and DeepSeek-V4.1
// checkpoints. Three tokenizer.json configurations share this
// implementation (DeepSeek-V4.1, 2026-09-13: no normalizer (an empty
// Sequence), THREE Split stages — number runs of at most three, CJK runs,
// its own main pattern over the \p{P}/\p{S} classes — then ByteLevel, BPE
// without ignore_merges). Loading rejects unsupported shapes and
// validates the following properties:
//   * pre-tokenizer: Sequence[Split (one of the two pinned GPT-2-family
//     regexes, Isolated), ByteLevel (map only, add_prefix_space=false,
//     use_regex=false)] — the regex string is matched exactly and the
//     scanner hardcodes both (text/unicode_tables.hpp carries the Unicode
//     predicates: GLM's pattern; Qwen's with [\p{L}\p{M}]+ letter runs, a
//     single \p{N}, and marks outside the punctuation class);
//   * normalizer: none (GLM) or NFC (Qwen; text/unicode_normalize.hpp);
//     post-processor: ByteLevel (offsets-only — no special tokens are
//     injected at encode);
//   * model: BPE with ignore_merges=true (GLM: whole-word vocab check
//     first) or false (Qwen: the merges always run), byte_fallback=false,
//     no unk (the 256 byte-level chars cover every byte), no
//     continuing/end-of-word prefixes;
//   * added tokens: plain matching (single_word/lstrip/rstrip all false).
// The pre-tokenizer's Unicode classes ride committed range tables
// (generated by tools/gen_unicode_tables.py, Unicode 15.0.0) — the
// version-skew caveat lives in that script's docstring.
//
// Validation uses differential golden tests against
// HF tokenizers 0.23.1 (tests/data/glm_tokenizer_goldens.jsonl — corpus,
// expected ids, and round-trip decodes), keyed by this file's revision
// hash (FNV-1a-64 of tokenizer.json): a gate run against a different
// tokenizer.json refuses rather than compares.
//
// Threading: load once, then encode/decode are const and thread-safe.
#include <cstdint>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "loaders/minijson.hpp"

namespace dgpp::text {

class Tokenizer {
 public:
  struct AddedToken {
    int64_t id = 0;
    std::string content;
    bool special = false;  // HF decode()'s skip_special_tokens skips these
  };

  // Loads and validates; throws std::runtime_error on any unsupported
  // shape (the message names the offending field).
  static Tokenizer load(const std::string& tokenizer_json_path);

  // text (UTF-8) -> ids. Added tokens match leftmost-longest and bypass
  // BPE; every other byte passes through the pinned pipeline (Split ->
  // ByteLevel -> BPE with ignore_merges).
  std::vector<int64_t> encode(std::string_view text) const;

  // ids -> text. HF 0.23's decode defaults to skip_special_tokens=true:
  // added tokens marked special are omitted; non-special ones decode
  // verbatim. skip_special_tokens=false decodes everything verbatim.
  std::string decode(const std::vector<int64_t>& ids,
                     bool skip_special_tokens = true) const;
  std::string decode(int64_t id, bool skip_special_tokens = true) const;

  // FNV-1a-64 over the raw tokenizer.json bytes — the golden corpus's
  // revision key.
  uint64_t revision_hash() const { return revision_hash_; }

  const std::vector<AddedToken>& added_tokens() const {
    return added_tokens_;
  }

  // Test/diagnostic accessors for the decode helper.
  size_t token_by_id_size() const { return token_by_id_.size(); }
  std::string_view token_by_id(size_t id) const {
    return token_by_id_[id];
  }
  int32_t cp_to_byte_at(uint32_t cp) const { return cp_to_byte_[cp]; }

  // Highest id encode can produce (the last added token's id).
  int64_t max_id() const { return max_id_; }

 private:
  struct MergeKey {
    std::string_view first;
    std::string_view second;
    bool operator==(const MergeKey& o) const {
      return first == o.first && second == o.second;
    }
  };
  struct MergeHash {
    size_t operator()(const MergeKey& k) const {
      return fnv1a(k.first) ^ (fnv1a(k.second) * 0x9e3779b97f4a7c15ull);
    }
    static uint64_t fnv1a(std::string_view s) {
      uint64_t h = 1469598103934665603ull;
      for (const char c : s) {
        h ^= static_cast<unsigned char>(c);
        h *= 1099511628211ull;
      }
      return h;
    }
  };
  struct TrieNode {
    int64_t id = -1;             // >= 0 → a token ends here
    int32_t child[256];           // byte trie; -1 = absent
  };

  // Appends `text`'s encoding to `out` (the added-token scan is caller-
  // driven; segments between added tokens come here).
  void encode_segment(std::string_view segment,
                      std::vector<int64_t>* out) const;
  // One pretoken's mapped symbol string -> ids (BPE, ignore_merges).
  void encode_word(std::string_view mapped, std::vector<int64_t>* out) const;

  // The raw file and its parse tree both stay members: minijson object
  // keys (Member.key) are tree-owned std::strings, so the vocab/merge keys
  // (string_views) remain valid only while the tree lives — the first
  // probe run crashed on exactly this (a find() walking a dead bucket).
  std::string json_buf_;
  minijson::ParseResult doc_;
  std::unordered_map<std::string_view, int64_t> vocab_;
  std::unordered_map<MergeKey, uint32_t, MergeHash> merge_rank_;
  std::vector<AddedToken> added_tokens_;
  std::vector<TrieNode> trie_;  // trie_[0] is the root
  // Dense base-vocab reverse map (decode-by-id); slot {} = missing (the
  // dense-coverage check at load rejects holes before this is used).
  std::vector<std::string_view> token_by_id_;
  // ByteLevel alphabet: byte -> codepoint, and the reverse map (filled at
  // load; mapped codepoints are all < 0x200).
  uint32_t byte_to_cp_[256] = {0};
  int32_t cp_to_byte_[0x200] = {0};
  uint64_t revision_hash_ = 0;
  int64_t max_id_ = -1;
  // The pinned shape this file matched at load.
  int pattern_ = 0;            // 0: the GLM regex, 1: the Qwen3.8 regex, 2: DeepSeek-V4.1 sequence, 3: MiMo single digits
  bool nfc_ = false;           // normalizer NFC (Qwen)
  bool ignore_merges_ = true;  // model.ignore_merges
};

}  // namespace dgpp::text
